baseURL = "https://www.u1s3.com"
# [en, zh-CN, ...] determines default content language
# [en, zh-CN, ...] 设置默认的语言
defaultContentLanguage = "en"
# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
# themesDir = "../.."

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = false
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # website title
    title = "U1S3"
    # language name
    languageName = "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-160608138-1"
    # copyright description used only for seo schema
    copyright = "CC BY-NC 4.0"
    # date format
    dateFormatToUse = "2006-01-02"
    # Menu Info
    [languages.en.menu]
      [[languages.en.menu.main]]       
        identifier = "posts"
        # you can add extra information before the name (HTML format is allowed), such as icons
        pre = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "favorites"
        pre = ""
        name = "Favorites"
        url = "/posts/favorites/"
        title = ""
        weight = 4
      [[languages.en.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        name = ""
        url = "https://github.com/chishuix"
        title = ""
        weight = 5
      [languages.en.params]
        # site description
        description = "有一说三，池水的一片海。 "
        # site keywords
        keywords = ["Theme", "Hugo"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "auto"
        # Home Page Info
        [languages.en.params.home]
          # Home Page Profile
          [languages.en.params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            gravatarEmail = ""
            # URL of avatar shown in home page
            avatarURL = "/images/avatar.jpeg"
            # subtitle shown in home page
            subtitle = "\"温柔的风啊，或是热烈的风啊。\""
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.en.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 5
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
          # Home Page Recommend
          [languages.en.params.home.recommends]
            enable = true
        # Social Info in home page
        [languages.en.params.social]
          GitHub = "xxxx"
          Linkedin = "xxxx"
          Twitter = "xxxx"
          Instagram = "xxxx"
          Email = "xxxx@xxxx.com"
          Facebook = "xxxx"
          Telegram = "xxxx"
          # Medium = "xxxx"
          # Gitlab = "xxxx"
          Youtubelegacy = "xxxx"
          # Youtubecustom = "xxxx"
          # Youtubechannel = "xxxx"
          # Tumblr ="xxxx"
          # Quora = "xxxx"
          # Keybase = "xxxx"
          # Pinterest = "xxxx"
          # Reddit = "xxxx"
          # Codepen = "xxxx"
          # FreeCodeCamp = "xxxx"
          # Bitbucket = "xxxx"
          # Stackoverflow = "xxxx"
          # Weibo = "xxxx"
          # Odnoklassniki = "xxxx"
          # VK = "xxxx"
          # Flickr = "xxxx"
          # Xing = "xxxx"
          # Snapchat = "xxxx"
          # Soundcloud = "xxxx"
          # Spotify = "xxxx"
          # Bandcamp = "xxxx"
          # Paypal = "xxxx"
          # Fivehundredpx = "xxxx"
          # Mix = "xxxx"
          # Goodreads = "xxxx"
          # Lastfm = "xxxx"
          # Foursquare = "xxxx"
          # Hackernews = "xxxx"
          # Kickstarter = "xxxx"
          # Patreon = "xxxx"
          # Steam = "xxxx"
          # Twitch = "xxxx"
          # Strava = "xxxx"
          # Skype = "xxxx"
          # Whatsapp = "xxxx"
          # Zhihu = "xxxx"
          # Douban = "xxxx"
          # Angellist = "xxxx"
          # Slidershare = "xxxx"
          # Jsfiddle = "xxxx"
          # Deviantart = "xxxx"
          # Behance = "xxxx"
          # Dribble = "xxxx"
          # Wordpress = "xxxx"
          # Vine = "xxxx"
          # Googlescholar = "xxxx"
          # Researchgate = "xxxx"
          # Mastodon = "xxxx"
          # MastodonPrefix = "https://mastodon.technology/"
          # Thingiverse = "xxxx"
          # Devto = "xxxx"
          # Gitea = "xxxx"
          # XMPP = "xxxx"
          # Matrix = "xxxx"
          # Bilibili = "xxxx"
        # Social Share Links in post page
        [languages.en.params.share]
          enable = false
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = true
          Pinterest = true
          # Tumblr = true
          HackerNews = true
          # Reddit = true
          # VK = true
          # Buffer = true
          # Xing = true
          # Line = true
          # Instapaper = true
          # Pocket = true
          # Digg = true
          # Stumbleupon = true
          # Flipboard = true
          # Weibo = true
          # Renren = true
          # Myspace = true
          # Blogger = true
          # Baidu = true
          # Odnoklassniki = true
          # Evernote = true
          # Skype = true
          # Trello = true
          # Mix = true
        # Comment Config
        [languages.en.params.comment]
          enable = false
          # Disqus Comment Config (https://disqus.com/)
          [languages.en.params.comment.disqus]
            # Disqus shortname to use Disqus in posts
            shortname = "dillonzq"
          # Gittalk Comment Config (https://github.com/gitalk/gitalk)
          [languages.en.params.comment.gitalk]
            owner = ""
            repo = ""
            clientId = ""
            clientSecret = ""
          # Valine Comment Config (https://github.com/xCss/Valine)
          [languages.en.params.comment.valine]
            enable = false
            appId = ""
            appKey = ""
            placeholder = "Your comment ..."
            notify = false
            verify = true
            avatar = "mp"
            meta= ""
            pageSize = 10
            lang = "en"
            visitor = true
            recordIP = true
          # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
          [languages.en.params.comment.facebook]
            enable = false
            width = "100%"
            numPosts = 10
            appId = ""
            languageCode = "en_US"

[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.1.X"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/dillonzq/LoveIt"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # Header info
  # 页面头部导航栏信息
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "normal"
    # mobile header mode ("fixed", "normal", "auto")
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "normal"
  # Footer Copyright Info
  # 页面底部版权信息设置
  [params.footer]
    # Site creation time
    # 网站创立年份
    since = 2017
    # ICP info only in China (HTML format is allowed)
    # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
    icp = "<a href='http://www.beian.miit.gov.cn/' target='_blank'>苏ICP备20010716号-1</a>"
    beian = "<a href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=32031102001246' target='_blank'> <img src='/beian.png' /> 苏公网安备 32031102001246号</a>"
    # license info (HTML format is allowed)
    # 许可协议信息 (允许使用 HTML 格式)
    # license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    license = ""
  # Page config
  # 文章页面配置
  [params.page]
    # whether to use lightgallery in the page
    # 是否在文章页面使用 lightgallery
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
  # mathematical formulas (KaTeX)
  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "chishui"
    [params.publisher.logo]
      url = "/images/logo.jpg"
      width = 127
      height = 40
  # Website Log Info just for SEO
  # 网站 Logo 信息，仅用于 SEO
  [params.logo]
    url = "/images/logo.jpg"
    width = 127
    height = 40
  # Website Image Info just for SEO
  # 网站图标信息，仅用于 SEO
  [params.image]
    url = "/images/cover.jpg"
    width = 800
    height = 600
  # CSS and JS Files CDN
  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = ''
    lightgalleryJS = ''
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = ''
    aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = ''
    echartsMacaronsJS = ''
    # gitalk@1.6.0 https://github.com/gitalk/gitalk
    gitalkCSS = ''
    gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    valineJS = ''

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 代码高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    # 代码高亮主题预览
    # https://xyproto.github.io/splash/docs/all.html 
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
# 作者信息
[author]
  name = "chishui"
  link = "/"

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":sections/:filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

